// <auto-generated />
using System;
using GitHubBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitHubBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927163521_AddInstallationId")]
    partial class AddInstallationId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitHubBot.Domain.Entities.ActionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_number");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("executed_at");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<Guid?>("RuleActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_action_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_event_id");

                    b.HasKey("Id");

                    b.HasIndex("RuleActionId");

                    b.HasIndex("WebhookEventId", "RuleActionId")
                        .IsUnique()
                        .HasDatabaseName("uq_action_executions_event_rule_action");

                    b.HasIndex("WebhookEventId", "RuleActionId", "Status")
                        .HasDatabaseName("idx_action_executions_lookup");

                    b.ToTable("action_executions", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.ConnectedRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("main")
                        .HasColumnName("default_branch");

                    b.Property<string>("EncryptedWebhookSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_webhook_secret");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<long>("GithubRepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_repository_id");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long?>("WebhookId")
                        .HasColumnType("bigint")
                        .HasColumnName("webhook_id");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("idx_connected_repositories_full_name");

                    b.HasIndex("GithubRepositoryId")
                        .IsUnique()
                        .HasDatabaseName("uq_connected_repositories_github_repo_id");

                    b.HasIndex("UserId");

                    b.ToTable("connected_repositories", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.GithubAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_access_token");

                    b.Property<long>("GithubUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_user_id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GithubUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_github_accounts_github_user_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_github_accounts_user_id");

                    b.ToTable("github_accounts", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "EventType")
                        .HasDatabaseName("idx_rules_repo_event")
                        .HasFilter("is_enabled = TRUE");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.RuleAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<int>("ExecutionOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("execution_order");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("rule_actions", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.RuleCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CaseSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("case_sensitive");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("condition_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("rule_conditions", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("claimed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6)
                        .HasColumnName("max_attempts");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("ParsedData")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_data");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedAt")
                        .HasDatabaseName("idx_webhook_events_stale_claims")
                        .HasFilter("status = 'Processing'");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_webhook_events_claimable")
                        .HasFilter("status IN ('Pending', 'Retrying')");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("uq_webhook_events_delivery_id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("webhook_events", (string)null);
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.ActionExecution", b =>
                {
                    b.HasOne("GitHubBot.Domain.Entities.RuleAction", "RuleAction")
                        .WithMany("ActionExecutions")
                        .HasForeignKey("RuleActionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GitHubBot.Domain.Entities.WebhookEvent", "WebhookEvent")
                        .WithMany("ActionExecutions")
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleAction");

                    b.Navigation("WebhookEvent");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.ConnectedRepository", b =>
                {
                    b.HasOne("GitHubBot.Domain.Entities.User", "User")
                        .WithMany("ConnectedRepositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.GithubAccount", b =>
                {
                    b.HasOne("GitHubBot.Domain.Entities.User", "User")
                        .WithOne("GithubAccount")
                        .HasForeignKey("GitHubBot.Domain.Entities.GithubAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.Rule", b =>
                {
                    b.HasOne("GitHubBot.Domain.Entities.ConnectedRepository", "Repository")
                        .WithMany("Rules")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.RuleAction", b =>
                {
                    b.HasOne("GitHubBot.Domain.Entities.Rule", "Rule")
                        .WithMany("Actions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.RuleCondition", b =>
                {
                    b.HasOne("GitHubBot.Domain.Entities.Rule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.WebhookEvent", b =>
                {
                    b.HasOne("GitHubBot.Domain.Entities.ConnectedRepository", "Repository")
                        .WithMany("WebhookEvents")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.ConnectedRepository", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("WebhookEvents");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.Rule", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.RuleAction", b =>
                {
                    b.Navigation("ActionExecutions");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.User", b =>
                {
                    b.Navigation("ConnectedRepositories");

                    b.Navigation("GithubAccount");
                });

            modelBuilder.Entity("GitHubBot.Domain.Entities.WebhookEvent", b =>
                {
                    b.Navigation("ActionExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
