<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GitHubBot.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitHubBot.Domain\GitHubBot.Domain.csproj" />
    <ProjectReference Include="..\GitHubBot.Application\GitHubBot.Application.csproj" />
  </ItemGroup>

</Project>
